services:
  hmas:
    build:
        context: ./HMAS
        dockerfile: Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    depends_on:
        - sql-server
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - hmas-network
    restart: 
        on-failure
    
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        SA_PASSWORD: "password123!"
        ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"
    volumes:
    - sqlvolume:/var/opt/mssql
    networks:
    - hmas-network
    restart: always
 
networks:
    hmas-network:
    
volumes:
    sqlvolume: